# -*- encoding: utf-8 -*-
from abjad import *


zagged_pitch_classes = pitchtools.PitchClassTree(
    [
        [
            [
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(1),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(4),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(11),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(7),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(9),
                pitchtools.NumberedPitchClass(10),
                pitchtools.NumberedPitchClass(0),
                pitchtools.NumberedPitchClass(8),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(6),
                ],
            [
                pitchtools.NumberedPitchClass(8),
                pitchtools.NumberedPitchClass(9),
                pitchtools.NumberedPitchClass(10),
                pitchtools.NumberedPitchClass(0),
                pitchtools.NumberedPitchClass(11),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(1),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(4),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(0),
                pitchtools.NumberedPitchClass(8),
                pitchtools.NumberedPitchClass(9),
                pitchtools.NumberedPitchClass(10),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(11),
                ],
            [
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(1),
                ],
            [
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(4),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(3),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(4),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(11),
                pitchtools.NumberedPitchClass(7),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(1),
                pitchtools.NumberedPitchClass(3),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(3),
                ],
            [
                pitchtools.NumberedPitchClass(10),
                pitchtools.NumberedPitchClass(0),
                pitchtools.NumberedPitchClass(8),
                pitchtools.NumberedPitchClass(9),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(9),
                ],
            [
                pitchtools.NumberedPitchClass(10),
                pitchtools.NumberedPitchClass(0),
                pitchtools.NumberedPitchClass(8),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(4),
                pitchtools.NumberedPitchClass(5),
                ],
            [
                pitchtools.NumberedPitchClass(11),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(1),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(8),
                pitchtools.NumberedPitchClass(9),
                pitchtools.NumberedPitchClass(10),
                pitchtools.NumberedPitchClass(0),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(1),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(4),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(11),
                pitchtools.NumberedPitchClass(7),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(1),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(4),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(11),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(0),
                pitchtools.NumberedPitchClass(8),
                pitchtools.NumberedPitchClass(9),
                pitchtools.NumberedPitchClass(10),
                ],
            [
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(3),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(10),
                ],
            [
                pitchtools.NumberedPitchClass(0),
                pitchtools.NumberedPitchClass(8),
                ],
            [
                pitchtools.NumberedPitchClass(9),
                pitchtools.NumberedPitchClass(11),
                pitchtools.NumberedPitchClass(7),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(1),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(4),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(9),
                pitchtools.NumberedPitchClass(10),
                pitchtools.NumberedPitchClass(0),
                pitchtools.NumberedPitchClass(8),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(11),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(1),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(4),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(7),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(4),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(11),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(1),
                pitchtools.NumberedPitchClass(3),
                ],
            [
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(5),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(8),
                pitchtools.NumberedPitchClass(9),
                pitchtools.NumberedPitchClass(10),
                ],
            [
                pitchtools.NumberedPitchClass(0),
                ],
            [
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(5),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(0),
                pitchtools.NumberedPitchClass(8),
                pitchtools.NumberedPitchClass(9),
                pitchtools.NumberedPitchClass(10),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(4),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(11),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(1),
                pitchtools.NumberedPitchClass(10),
                pitchtools.NumberedPitchClass(0),
                pitchtools.NumberedPitchClass(8),
                pitchtools.NumberedPitchClass(9),
                ],
            ],
        [
            [
                pitchtools.NumberedPitchClass(1),
                pitchtools.NumberedPitchClass(3),
                pitchtools.NumberedPitchClass(4),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(11),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(5),
                pitchtools.NumberedPitchClass(6),
                pitchtools.NumberedPitchClass(7),
                pitchtools.NumberedPitchClass(3),
                ],
            ],
        ]
    )