import baca


def test_InstrumentationEditor_round_trips_01():
    '''Round trip.
    '''
    
    editor = baca.scf.editors.InstrumentationEditor()
    editor.run(user_input='add 1 1 add 2 1 mv 1 2 del 2 q')
    assert editor.transcript == \
    [['Performers', '', '     add performers', ''],
     ['SCF> add', ''],
     ['Performers - add performers',
      '',
      '     1: accordionist',
      '     2: bassist',
      '     3: bassoonist',
      '     4: cellist',
      '     5: clarinetist',
      '     6: flutist',
      '     7: guitarist',
      '     8: harpist',
      '     9: hornist',
      '     10: oboist',
      '     11: percussionist',
      '     12: pianist',
      '     13: trombonist',
      '     14: trumpeter',
      '     15: tubist',
      '     16: violinist',
      '     17: violist',
      ''],
     ['SCF> 1', ''],
     ['Performers - add performers - accordionist',
      '',
      '     Select instruments',
      '',
      '     1: accordion (default)',
      '',
      '     other instruments',
      '     no instruments',
      ''],
     ['SCF> 1', ''],
     ['Performers',
      '',
      '     1: accordionist (accordion)',
      '',
      '     add performers',
      '     delete performers',
      ''],
     ['SCF> add', ''],
     ['Performers - add performers',
      '',
      '     1: accordionist',
      '     2: bassist',
      '     3: bassoonist',
      '     4: cellist',
      '     5: clarinetist',
      '     6: flutist',
      '     7: guitarist',
      '     8: harpist',
      '     9: hornist',
      '     10: oboist',
      '     11: percussionist',
      '     12: pianist',
      '     13: trombonist',
      '     14: trumpeter',
      '     15: tubist',
      '     16: violinist',
      '     17: violist',
      ''],
     ['SCF> 2', ''],
     ['Performers - add performers - bassist',
      '',
      '     Select instruments',
      '',
      '     1: contrabass (default)',
      '',
      '     other instruments',
      '     no instruments',
      ''],
     ['SCF> 1', ''],
     ['Performers',
      '',
      '     1: accordionist (accordion)',
      '     2: bassist (contrabass)',
      '',
      '     add performers',
      '     delete performers',
      '     move performers',
      ''],
     ['SCF> mv', ''],
     ['Old number> 1', ''],
     ['New number> 2', ''],
     ['Performers',
      '',
      '     1: bassist (contrabass)',
      '     2: accordionist (accordion)',
      '',
      '     add performers',
      '     delete performers',
      '     move performers',
      ''],
     ['SCF> del', ''],
     ['Performer numbers> 2', ''],
     ['Performers',
      '',
      '     1: bassist (contrabass)',
      '',
      '     add performers',
      '     delete performers',
      ''],
     ['SCF> q', '']]
