#! /usr/bin/env python

import os

os.system('clear')

dirs = (
   '/Users/trevorbaca/Documents/abjad',
   '/Users/trevorbaca/Documents/friends',
   '/Users/trevorbaca/Documents/harvard',
   )

for dir in dirs:
   name = dir.split('/')[-1]
   print '%s ...' % name
   os.system('svn up %s' % dir)
   print ''

others = os.listdir(os.getenv('MISCELLANEOUS'))
others = [x for x in others if not x.startswith('.')]
for other in others:
   print '%s ...' % other
   repository = os.path.join(os.getenv('MISCELLANEOUS'), other)
   os.system('svn up %s' % repository)
   print ''

scores = os.listdir(os.getenv('SCORES'))
scores = [x for x in scores if not x.startswith('.')]
for score in scores:
   print '%s ...' % score
   repository = os.path.join(os.getenv('SCORES'), score)
   os.system('svn up %s' % repository)
   print ''
