"""
Tags.
"""

import abjad

# BAR EXTENT

EXPLICIT_BAR_EXTENT = abjad.Tag("EXPLICIT_BAR_EXTENT")
REAPPLIED_BAR_EXTENT = abjad.Tag("REAPPLIED_BAR_EXTENT")
REDUNDANT_BAR_EXTENT = abjad.Tag("REDUNDANT_BAR_EXTENT")

# CLEF

EXPLICIT_CLEF = abjad.Tag("EXPLICIT_CLEF")
EXPLICIT_CLEF_COLOR = abjad.Tag("EXPLICIT_CLEF_COLOR")
EXPLICIT_CLEF_COLOR_CANCELLATION = abjad.Tag("EXPLICIT_CLEF_COLOR_CANCELLATION")
EXPLICIT_CLEF_REDRAW_COLOR = abjad.Tag("EXPLICIT_CLEF_REDRAW_COLOR")
REAPPLIED_CLEF = abjad.Tag("REAPPLIED_CLEF")
REAPPLIED_CLEF_COLOR = abjad.Tag("REAPPLIED_CLEF_COLOR")
REAPPLIED_CLEF_COLOR_CANCELLATION = abjad.Tag("REAPPLIED_CLEF_COLOR_CANCELLATION")
REAPPLIED_CLEF_REDRAW_COLOR = abjad.Tag("REAPPLIED_CLEF_REDRAW_COLOR")
REDUNDANT_CLEF = abjad.Tag("REDUNDANT_CLEF")
REDUNDANT_CLEF_COLOR = abjad.Tag("REDUNDANT_CLEF_COLOR")
REDUNDANT_CLEF_COLOR_CANCELLATION = abjad.Tag("REDUNDANT_CLEF_COLOR_CANCELLATION")
REDUNDANT_CLEF_REDRAW_COLOR = abjad.Tag("REDUNDANT_CLEF_REDRAW_COLOR")

# DOCUMENT ANNOTATIONS

ANCHOR_NOTE = abjad.Tag("ANCHOR_NOTE")
ANCHOR_SKIP = abjad.Tag("ANCHOR_SKIP")
CLOCK_TIME = abjad.Tag("CLOCK_TIME")
FERMATA_MEASURE = abjad.Tag("FERMATA_MEASURE")
FERMATA_MEASURE = abjad.Tag("FERMATA_MEASURE")
FERMATA_MEASURE_EMPTY_BAR_EXTENT = abjad.Tag("FERMATA_MEASURE_EMPTY_BAR_EXTENT")
FERMATA_MEASURE_NEXT_BAR_EXTENT = abjad.Tag("FERMATA_MEASURE_NEXT_BAR_EXTENT")
FERMATA_MEASURE_RESUME_BAR_EXTENT = abjad.Tag("FERMATA_MEASURE_RESUME_BAR_EXTENT")
FIGURE_LABEL = abjad.Tag("FIGURE_LABEL")
HIDDEN = abjad.Tag("HIDDEN")
HIDE_IN_PARTS = abjad.Tag("HIDE_IN_PARTS")
INVISIBLE_MUSIC_COLORING = abjad.Tag("INVISIBLE_MUSIC_COLORING")
INVISIBLE_MUSIC_COMMAND = abjad.Tag("INVISIBLE_MUSIC_COMMAND")
LOCAL_MEASURE_NUMBER = abjad.Tag("LOCAL_MEASURE_NUMBER")
MEASURE_NUMBER = abjad.Tag("MEASURE_NUMBER")
MOMENT_NUMBER = abjad.Tag("MOMENT_NUMBER")
MULTIMEASURE_REST = abjad.Tag("MULTIMEASURE_REST")
NOT_MOL = abjad.Tag("NOT_MOL")
NOTE = abjad.Tag("NOTE")
ONLY_MOL = abjad.Tag("ONLY_MOL")
RED_START_BAR = abjad.Tag("RED_START_BAR")
REST_VOICE = abjad.Tag("REST_VOICE")
SHIFTED_CLEF = abjad.Tag("SHIFTED_CLEF")
SHOW_IN_PARTS = abjad.Tag("SHOW_IN_PARTS")
SKIP = abjad.Tag("SKIP")
SPACING = abjad.Tag("SPACING")
STAFF_HIGHLIGHT = abjad.Tag("STAFF_HIGHLIGHT")
STAGE_NUMBER = abjad.Tag("STAGE_NUMBER")

# DOCUMENT TYPE RESTRICTIONS

# TODO: remove + and - prefixes
NOT_PARTS = abjad.Tag("-PARTS")
NOT_SCORE = abjad.Tag("-SCORE")
NOT_SECTION = abjad.Tag("-SECTION")
ONLY_PARTS = abjad.Tag("+PARTS")
ONLY_SCORE = abjad.Tag("+SCORE")
ONLY_SECTION = abjad.Tag("+SECTION")

# DOCUMENT TYPES

BUILD = abjad.Tag("BUILD")
PARTS = abjad.Tag("PARTS")
SCORE = abjad.Tag("SCORE")
SECTION = abjad.Tag("SECTION")

# DYNAMIC

EXPLICIT_DYNAMIC = abjad.Tag("EXPLICIT_DYNAMIC")
EXPLICIT_DYNAMIC_COLOR = abjad.Tag("EXPLICIT_DYNAMIC_COLOR")
REAPPLIED_DYNAMIC = abjad.Tag("REAPPLIED_DYNAMIC")
REAPPLIED_DYNAMIC_COLOR = abjad.Tag("REAPPLIED_DYNAMIC_COLOR")
REDUNDANT_DYNAMIC = abjad.Tag("REDUNDANT_DYNAMIC")
REDUNDANT_DYNAMIC_COLOR = abjad.Tag("REDUNDANT_DYNAMIC_COLOR")

# FIGURES

FORESHADOW = abjad.Tag("FORESHADOW")
INCOMPLETE = abjad.Tag("INCOMPLETE")
RECOLLECTION = abjad.Tag("RECOLLECTION")

# FRAMED LEAVES

FRAMED_LEAF = abjad.Tag("FRAMED_LEAF")

# IMPORTANT COMMANDS

ONE_VOICE_COMMAND = abjad.Tag("ONE_VOICE_COMMAND")

# INSTRUMENT

EXPLICIT_INSTRUMENT = abjad.Tag("EXPLICIT_INSTRUMENT")
EXPLICIT_INSTRUMENT_ALERT = abjad.Tag("EXPLICIT_INSTRUMENT_ALERT")
EXPLICIT_INSTRUMENT_COLOR = abjad.Tag("EXPLICIT_INSTRUMENT_COLOR")
REDRAWN_EXPLICIT_INSTRUMENT = abjad.Tag("REDRAWN_EXPLICIT_INSTRUMENT")
REDRAWN_EXPLICIT_INSTRUMENT_COLOR = abjad.Tag("REDRAWN_EXPLICIT_INSTRUMENT_COLOR")
REAPPLIED_INSTRUMENT = abjad.Tag("REAPPLIED_INSTRUMENT")
REAPPLIED_INSTRUMENT_ALERT = abjad.Tag("REAPPLIED_INSTRUMENT_ALERT")
REAPPLIED_INSTRUMENT_COLOR = abjad.Tag("REAPPLIED_INSTRUMENT_COLOR")
REDRAWN_REAPPLIED_INSTRUMENT = abjad.Tag("REDRAWN_REAPPLIED_INSTRUMENT")
REDRAWN_REAPPLIED_INSTRUMENT_COLOR = abjad.Tag("REDRAWN_REAPPLIED_INSTRUMENT_COLOR")
REDUNDANT_INSTRUMENT = abjad.Tag("REDUNDANT_INSTRUMENT")
REDUNDANT_INSTRUMENT_ALERT = abjad.Tag("REDUNDANT_INSTRUMENT_ALERT")
REDUNDANT_INSTRUMENT_COLOR = abjad.Tag("REDUNDANT_INSTRUMENT_COLOR")
REDRAWN_REDUNDANT_INSTRUMENT = abjad.Tag("REDRAWN_REDUNDANT_INSTRUMENT")
REDRAWN_REDUNDANT_INSTRUMENT_COLOR = abjad.Tag("REDRAWN_REDUNDANT_INSTRUMENT_COLOR")

# MATERIAL ANNOTATION

MATERIAL_ANNOTATION_MARKUP = abjad.Tag("MATERIAL_ANNOTATION_MARKUP")
MATERIAL_ANNOTATION_SPANNER = abjad.Tag("MATERIAL_ANNOTATION_SPANNER")

# METRONOME MARK

EXPLICIT_METRONOME_MARK = abjad.Tag("EXPLICIT_METRONOME_MARK")
EXPLICIT_METRONOME_MARK_WITH_COLOR = abjad.Tag("EXPLICIT_METRONOME_MARK_WITH_COLOR")
LILYPOND_TEMPO_COMMAND = abjad.Tag("LILYPOND_TEMPO_COMMAND")
REAPPLIED_METRONOME_MARK = abjad.Tag("REAPPLIED_METRONOME_MARK")
REAPPLIED_METRONOME_MARK_WITH_COLOR = abjad.Tag("REAPPLIED_METRONOME_MARK_WITH_COLOR")
REDUNDANT_METRONOME_MARK = abjad.Tag("REDUNDANT_METRONOME_MARK")
REDUNDANT_METRONOME_MARK_WITH_COLOR = abjad.Tag("REDUNDANT_METRONOME_MARK_WITH_COLOR")

# METRONOME MARK SPANNER

METRIC_MODULATION_IS_NOT_SCALED = abjad.Tag("METRIC_MODULATION_IS_NOT_SCALED")
METRIC_MODULATION_IS_SCALED = abjad.Tag("METRIC_MODULATION_IS_SCALED")
METRIC_MODULATION_IS_STRIPPED = abjad.Tag("METRIC_MODULATION_IS_STRIPPED")

# NOT TOPMOST

NOT_TOPMOST = abjad.Tag("NOT_TOPMOST")


# OTTAVA

EXPLICIT_OTTAVA = abjad.Tag("EXPLICIT_OTTAVA")
EXPLICIT_OTTAVA_COLOR = abjad.Tag("EXPLICIT_OTTAVA_COLOR")
REAPPLIED_OTTAVA = abjad.Tag("REAPPLIED_OTTAVA")
REAPPLIED_OTTAVA_COLOR = abjad.Tag("REAPPLIED_OTTAVA_COLOR")
REAPPLIED_OTTAVA_COLOR = abjad.Tag("REAPPLIED_OTTAVA_COLOR")
REDUNDANT_OTTAVA = abjad.Tag("REDUNDANT_OTTAVA")
REDUNDANT_OTTAVA_COLOR = abjad.Tag("REDUNDANT_OTTAVA_COLOR")

# PERSISTENT OVERRIDE

EXPLICIT_PERSISTENT_OVERRIDE = abjad.Tag("EXPLICIT_PERSISTENT_OVERRIDE")
REAPPLIED_PERSISTENT_OVERRIDE = abjad.Tag("REAPPLIED_PERSISTENT_OVERRIDE")
REDUNDANT_PERSISTENT_OVERRIDE = abjad.Tag("REDUNDANT_PERSISTENT_OVERRIDE")

# PITCH COLORINGS

MOCK_COLORING = abjad.Tag("MOCK_COLORING")
NOT_YET_PITCHED_COLORING = abjad.Tag("NOT_YET_PITCHED_COLORING")
NOT_YET_REGISTERED_COLORING = abjad.Tag("NOT_YET_REGISTERED_COLORING")
OCTAVE_COLORING = abjad.Tag("OCTAVE_COLORING")
OUT_OF_RANGE_COLORING = abjad.Tag("OUT_OF_RANGE_COLORING")
REPEAT_PITCH_CLASS_COLORING = abjad.Tag("REPEAT_PITCH_CLASS_COLORING")

# RHYTHM

DURATION_MULTIPLIER = abjad.Tag("DURATION_MULTIPLIER")

# SHORT INSTRUMET NAME

EXPLICIT_SHORT_INSTRUMENT_NAME = abjad.Tag("EXPLICIT_SHORT_INSTRUMENT_NAME")
EXPLICIT_SHORT_INSTRUMENT_NAME_ALERT = abjad.Tag("EXPLICIT_SHORT_INSTRUMENT_NAME_ALERT")
EXPLICIT_SHORT_INSTRUMENT_NAME_COLOR = abjad.Tag("EXPLICIT_SHORT_INSTRUMENT_NAME_COLOR")
REDRAWN_EXPLICIT_SHORT_INSTRUMENT_NAME = abjad.Tag(
    "REDRAWN_EXPLICIT_SHORT_INSTRUMENT_NAME"
)
REDRAWN_EXPLICIT_SHORT_INSTRUMENT_NAME_COLOR = abjad.Tag(
    "REDRAWN_EXPLICIT_SHORT_INSTRUMENT_NAME_COLOR"
)
REAPPLIED_SHORT_INSTRUMENT_NAME = abjad.Tag("REAPPLIED_SHORT_INSTRUMENT_NAME")
REAPPLIED_SHORT_INSTRUMENT_NAME_ALERT = abjad.Tag(
    "REAPPLIED_SHORT_INSTRUMENT_NAME_ALERT"
)
REAPPLIED_SHORT_INSTRUMENT_NAME_COLOR = abjad.Tag(
    "REAPPLIED_SHORT_INSTRUMENT_NAME_COLOR"
)
REDRAWN_REAPPLIED_SHORT_INSTRUMENT_NAME = abjad.Tag(
    "REDRAWN_REAPPLIED_SHORT_INSTRUMENT_NAME"
)
REDRAWN_REAPPLIED_SHORT_INSTRUMENT_NAME_COLOR = abjad.Tag(
    "REDRAWN_REAPPLIED_SHORT_INSTRUMENT_NAME_COLOR"
)
REDUNDANT_SHORT_INSTRUMENT_NAME = abjad.Tag("REDUNDANT_SHORT_INSTRUMENT_NAME")
REDUNDANT_SHORT_INSTRUMENT_NAME_ALERT = abjad.Tag(
    "REDUNDANT_SHORT_INSTRUMENT_NAME_ALERT"
)
REDUNDANT_SHORT_INSTRUMENT_NAME_COLOR = abjad.Tag(
    "REDUNDANT_SHORT_INSTRUMENT_NAME_COLOR"
)
REDRAWN_REDUNDANT_SHORT_INSTRUMENT_NAME = abjad.Tag(
    "REDRAWN_REDUNDANT_SHORT_INSTRUMENT_NAME"
)
REDRAWN_REDUNDANT_SHORT_INSTRUMENT_NAME_COLOR = abjad.Tag(
    "REDRAWN_REDUNDANT_SHORT_INSTRUMENT_NAME_COLOR"
)

# SPACING SECTION

EXPLICIT_SPACING_SECTION = abjad.Tag("EXPLICIT_SPACING_SECTION")
EXPLICIT_SPACING_SECTION_COLOR = abjad.Tag("EXPLICIT_SPACING_SECTION_COLOR")
REAPPLIED_SPACING_SECTION = abjad.Tag("REAPPLIED_SPACING_SECTION")
REAPPLIED_SPACING_SECTION_COLOR = abjad.Tag("REAPPLIED_SPACING_SECTION_COLOR")
REDUNDANT_SPACING_SECTION = abjad.Tag("REDUNDANT_SPACING_SECTION")
REDUNDANT_SPACING_SECTION_COLOR = abjad.Tag("REDUNDANT_SPACING_SECTION_COLOR")

# SPANNERS BROKEN

AUTODETECT = abjad.Tag("AUTODETECT")
HIDE_TO_JOIN_BROKEN_SPANNERS = abjad.Tag("HIDE_TO_JOIN_BROKEN_SPANNERS")
LEFT_BROKEN = abjad.Tag("LEFT_BROKEN")
RIGHT_BROKEN = abjad.Tag("RIGHT_BROKEN")
RIGHT_BROKEN_SHOW_NEXT = abjad.Tag("RIGHT_BROKEN_SHOW_NEXT")
SHOW_TO_JOIN_BROKEN_SPANNERS = abjad.Tag("SHOW_TO_JOIN_BROKEN_SPANNERS")

# SPANNERS CUSTOM

EOS_STOP_MM_SPANNER = abjad.Tag("EOS_STOP_MM_SPANNER")
METRIC_MODULATION_SPANNER = abjad.Tag("METRIC_MODULATION_SPANNER")
MOMENT_ANNOTATION_SPANNER = abjad.Tag("MOMENT_ANNOTATION_SPANNER")

# SPANNERS OTHER

SPANNER_START = abjad.Tag("SPANNER_START")
SPANNER_STOP = abjad.Tag("SPANNER_STOP")

# STAFF LINES

EXPLICIT_STAFF_LINES = abjad.Tag("EXPLICIT_STAFF_LINES")
EXPLICIT_STAFF_LINES_COLOR = abjad.Tag("EXPLICIT_STAFF_LINES_COLOR")
REAPPLIED_STAFF_LINES = abjad.Tag("REAPPLIED_STAFF_LINES")
REAPPLIED_STAFF_LINES_COLOR = abjad.Tag("REAPPLIED_STAFF_LINES_COLOR")
REDUNDANT_STAFF_LINES = abjad.Tag("REDUNDANT_STAFF_LINES")
REDUNDANT_STAFF_LINES_COLOR = abjad.Tag("REDUNDANT_STAFF_LINES_COLOR")

# TIME SIGNATURE

EXPLICIT_TIME_SIGNATURE = abjad.Tag("EXPLICIT_TIME_SIGNATURE")
EXPLICIT_TIME_SIGNATURE_COLOR = abjad.Tag("EXPLICIT_TIME_SIGNATURE_COLOR")
REAPPLIED_TIME_SIGNATURE = abjad.Tag("REAPPLIED_TIME_SIGNATURE")
REAPPLIED_TIME_SIGNATURE_COLOR = abjad.Tag("REAPPLIED_TIME_SIGNATURE_COLOR")
REDUNDANT_TIME_SIGNATURE = abjad.Tag("REDUNDANT_TIME_SIGNATURE")
REDUNDANT_TIME_SIGNATURE_COLOR = abjad.Tag("REDUNDANT_TIME_SIGNATURE_COLOR")


def tag(wrappers: list[abjad.wrapper.Wrapper], *tags: abjad.Tag):
    for wrapper in wrappers:
        for tag in tags:
            tag_ = wrapper.get_tag().append(tag)
            wrapper.set_tag(tag_)
