#! /usr/bin/env bash

current_directory=$(pwd)
read -p "Enter commit message> " COMMIT_MESSAGE

clear;
for repo in $(ls -d "$SCORES"/*/); do
    cd "$repo";
    echo $(pwd) ...;
    git add -A "$repo";
    git commit -m "${COMMIT_MESSAGE}" "$repo";
    git push;
done
