#! /usr/bin/env python

import os

os.system('clear')

dirs = (
   '/Users/trevorbaca/Documents/friends',

   '/Users/trevorbaca/Documents/abjad',
   '/Users/trevorbaca/Documents/abjad/baca',

   '/Users/trevorbaca/Documents/harvard',

   '/Users/trevorbaca/Documents/other/articles',
   '/Users/trevorbaca/Documents/other/math',
   '/Users/trevorbaca/Documents/other/monographs',
   '/Users/trevorbaca/Documents/other/reference',
   '/Users/trevorbaca/Documents/other/travel',
   '/Users/trevorbaca/Documents/other/vitae',

   '/Users/trevorbaca/Documents/scores/recursif',
   '/Users/trevorbaca/Documents/scores/hijinks',
   '/Users/trevorbaca/Documents/scores/cary',
   '/Users/trevorbaca/Documents/scores/sekka',
   '/Users/trevorbaca/Documents/scores/lidercfeny',
   '/Users/trevorbaca/Documents/scores/manifolds',
   '/Users/trevorbaca/Documents/scores/territoires',
   '/Users/trevorbaca/Documents/scores/desir',
   )

for dir in dirs:
   name = dir.split('/')[-1]
   print '%s ...' % name
   os.system('svn st -u %s' % dir)
   print ''
