#! /usr/bin/env python

import os

os.system('clear')

environment_variables = (
   'BACA',
   'FRIENDS',
   'HARVARD',
   'MISCELLANEOUS',
   )

for environment_variable in environment_variables:
   path_name = os.environ.get(environment_variable)
   directory_name = path_name.split(os.path.sep)[-1]
   print '%s ...' % directory_name
   os.system('svn st -u %s' % path_name)
   print ''

scores = os.listdir(os.getenv('SCORES'))
scores = [x for x in scores if not x.startswith('.')]
for score in scores:
   print '%s ...' % score
   repository = os.path.join(os.getenv('SCORES'), score)
   os.system('svn st -u %s' % repository)
   print ''