#! /usr/bin/env python
import pathlib
import sys


if __name__ == "__main__":
    target = pathlib.Path(sys.argv[1])
    key = sys.argv[2]
    value = sys.argv[3]
    values = {key: value}
    template = target.read_text()
    template = template.format(**values)
    target.write_text(template)
