#! /usr/bin/env python
"""
Call from a single part directory.

A short driver script will benecessary to loop this script over all part directories
in a build.
"""
import io
import os
import shutil
import subprocess
import sys

import helpers

import abjad
import baca

for string in sys.argv[1:]:
    if string.startswith("--directory="):
        directory = string[12:]
        break
else:
    directory = os.getcwd()
directory = baca.Path(directory)

if not directory.is_part():
    print("Must run script in part build directory ...")
    sys.exit(-1)

file_name = directory.name + "-music.ly"
path = directory / file_name
part = baca.segments.path_to_part(path)
dashed_part_name = abjad.String(part.name).to_dash_case()
part_directory = directory
part_pdf_path = part_directory / dashed_part_name
part_pdf_path = part_pdf_path.with_suffix(".pdf")
print(f"Building {part_pdf_path.trim()} ...")
snake_part_name = abjad.String(part.name).to_snake_case()
file_name = f"{snake_part_name}_layout.py"
path = part_directory / file_name
helpers._make_layout_ly(path)
print()
file_name = f"{dashed_part_name}-front-cover.tex"
path = part_directory / file_name
helpers._interpret_tex_file(path)
print()
file_name = f"{dashed_part_name}-preface.tex"
path = part_directory / file_name
helpers._interpret_tex_file(path)
print()
file_name = f"{dashed_part_name}-music.ly"
path = part_directory / file_name
LOG = part_directory / "lilypond.log"
helpers._run_lilypond(path)
print()
file_name = f"{dashed_part_name}-back-cover.tex"
path = part_directory / file_name
helpers._interpret_tex_file(path)
print()
file_name = f"{dashed_part_name}-part.tex"
path = part_directory / file_name
helpers._interpret_tex_file(path)
if "--do-not-open" not in sys.argv[1:]:
    file_name = f"{dashed_part_name}-part.pdf"
    path = part_directory / file_name
    os.system(f"open {path}")
