#! /usr/bin/env python
import baca

if __name__ == "__main__":
    arguments = baca.build.arguments("--debug-sections")
    baca.build.build_score(
        baca.build.directory(),
        debug_sections=arguments.debug_sections,
    )
