#! /usr/bin/env bash

RC=0
for path in $(find . -name definition.py | sort); do
    echo -n "Checking $path ... "
    SECONDS=0
    python $path 1>/dev/null 2>&1
    if [ $? -eq 0 ]; then
        echo OK "($SECONDS sec.)"
    else
        RC=1
        echo FAIL "($SECONDS sec.)"
    fi
done
echo
exit $RC
