#! /usr/bin/env python
import os
import pathlib

import baca

if __name__ == "__main__":
    directory = os.getcwd()
    directory = pathlib.Path(directory)
    assert directory.parent.name == "builds", repr(directory)
    _sections_directory = directory / "_sections"
    baca.build.collect_section_lys(_sections_directory)
