#! /usr/bin/env python
import os
import sys

import baca

if __name__ == "__main__":
    directory = os.getcwd()
    arguments = baca.build.arguments("--undo")
    baca.build.color_persistent_indicators(directory, undo=arguments.undo)
