#! /usr/bin/env bash

source realpath

paths=$(find . -name definition.py | sort)
RC=0

for path in $paths; do
    echo "Checking definition ..."
    FILE=$(realpath $path)
    SECONDS=0
    python $FILE
    if [ "$?" -ne 0 ]; then
        RC=1
    fi
    if [ "$?" -eq 0 ]; then
        echo $FILE ... OK
    fi
    if [ "$SECONDS" -eq 1 ]; then
        echo "Total time ${SECONDS} second ..."
    else
        echo "Total time ${SECONDS} seconds ..."
    fi
    echo
done

exit $RC
