#! /usr/bin/env python

import os

os.system('clear')

dirs = (
   '/Users/trevorbaca/friends',
   )

for dir in dirs:
   name = dir.split('/')[-1]
   print '%s ...' % name
   os.system('svn st -u %s' % dir)
   print ''
