#! /usr/bin/env python
"""
This script only works with scores that make container_to_part_assignment settings.

Create music.ly files by hand for part builds in other scores.
"""
import os
import shutil
import sys

import helpers

import abjad
import baca

directory = os.getcwd()
directory = baca.Path(directory)
if directory.parent.name != "builds":
    print("Call script in part build directory ...")
    sys.exit(-1)

part_directories = []
for path_ in sorted(directory.iterdir()):
    if not path_.is_dir():
        continue
    if not path_.name[0].isalpha():
        continue
    part_directories.append(path_)
if not part_directories:
    sys.exit()

part_directory_count = len(part_directories)
for i, part_directory in enumerate(part_directories):
    path = part_directory / "music.ly"
    part = baca.segments.path_to_part(path)
    if part is None:
        print(f"Skipping {path.parent.trim()} ...")
        continue
    assert isinstance(part, baca.segments.Part)
    dashed_part_name = abjad.String(part.name).to_dash_case()
    file_name = f"{dashed_part_name}-music.ly"
    assert path.build is not None
    path = path.build / file_name
    forces_tagline = helpers._part_subtitle(part.name) + " part"
    part_subtitle = helpers._part_subtitle(part.name, parentheses=True)
    helpers._generate_part_music_ly(
        path,
        dashed_part_name=dashed_part_name,
        forces_tagline=forces_tagline,
        keep_with_tag=part.name,
        part=part,
        part_subtitle=part_subtitle,
    )
    if 0 < part_directory_count and i + 1 < part_directory_count:
        print()
