#! /usr/bin/env python
import os
import sys

import ide
from ide.AbjadIDE import _get_repository_root

import abjad


def _git_st(directory):
    if not _get_repository_root(directory):
        print(f"missing {directory.trim()} repository ...")
        return
    with abjad.TemporaryDirectoryChange(directory=directory):
        command = "git status ."
        print(f"Running {command} ...")
        lines = abjad.iox.run_command(command)
        for line in lines:
            print(line)
        print()
    

if __name__ == "__main__":
    os.system("clear")
    for path in ide.Path("/Users/trevorbaca/Scores").list_paths():
        print(f"{path} ...")
        _git_st(path)
