#! /usr/bin/env bash

package_name=$(basename "$GITHUB_WORKSPACE")
wrapper_directory=$GITHUB_WORKSPACE
contents_directory=$wrapper_directory/$package_name
segments_directory=$contents_directory/segments
if [ ! -d $segments_directory/01 ]; then
    echo Score contains no segments ...
    exit 0
fi
GREEN_BOLD='\033[1;32m'
RED_BOLD='\033[1;31m'
NC='\033[0m'
for segment_directory in $(ls -d "$segments_directory"/[0-9]*); do
    result=0
    cd $segment_directory
    clicktrack_midi=$segment_directory/clicktrack.midi
    layout_ly=$segment_directory/layout.ly
    layout_py=$segment_directory/layout.py
    music_ily=$segment_directory/music.ily
    music_ly=$segment_directory/music.ly
    music_midi=$segment_directory/music.midi
    music_pdf=$segment_directory/music.pdf
    # remove existing output files
    if [ -f clicktrack.midi ]; then rm clicktrack.midi; fi
    if [ -f layout.ly ]; then rm layout.ly; fi
    if [ -f music.ily ]; then rm music.ily; fi
    if [ -f music.ly ]; then rm music.ly; fi
    if [ -f music.midi ]; then rm music.midi; fi
    if [ -f music.pdf ]; then rm music.pdf; fi
    clicktrack_midi_same=0
    layout_ly_same=0
    music_ily_same=0
    music_ly_same=0
    music_midi_same=0
    # run scripts
    if [ -f layout.py ]; then
        python layout.py --print-file-handling
    fi
    python music.py --clicktrack --midi --pdf --print-file-handling
    # capture diffs
    if [ -f clicktrack.midi ]; then
        output=$(git diff --color=always -I"\version.*" clicktrack.midi)
        if [ "$output" ]; then
            echo "$output" | head -30
            result=99
        else
            clicktrack_midi_same=1
        fi
    fi
    if [ -f layout.ly ]; then
        output=$(git diff --color=always layout.ly)
        if [ "$output" ]; then
        echo "$output" | head -30
        result=99
        else
            layout_ly_same=1
        fi
    fi
    if [ -f music.ily ]; then
        output=$(git diff --color=always -I"\version.*" music.ily)
        if [ "$output" ]; then
            echo "$output" | head -30
            result=99
        else
            music_ily_same=1
        fi
    fi
    if [ -f music.ly ]; then 
        output=$(git diff --color=always -I"\version.*" music.ly)
        if [ "$output" ]; then
            echo "$output" | head -30
            result=99
        else
            music_ly_same=1
        fi
    fi
    if [ -f music.midi ]; then
        output=$(git diff --color=always -I"\version.*" music.midi)
        if [ "$output" ]; then
            echo "$output" | head -30
            result=99
        else
            music_midi_same=1
        fi
    fi
    if [ ! -f music.pdf ]; then
        if [ -f .music.ly.log ]; then
            cat .music.ly.log
        fi
    fi
    # print creation results
    if [ -f clicktrack.midi ]; then
        echo -e "${GREEN_BOLD}PASS:${NC} $clicktrack_midi found ..."
    else
        echo -e "${RED_BOLD}FAIL:${NC} $clicktrack_midi missing ..."
        result=99
    fi
    if [ -f layout.py ]; then
        if [ -f layout.ly ]; then
        echo -e "${GREEN_BOLD}PASS:${NC} $layout_ly found ..."
        else
        echo -e "${RED_BOLD}FAIL:${NC} $layout_ly missing ..."
        result=99
        fi
    fi
    if [ -f music.ily ]; then
        echo -e "${GREEN_BOLD}PASS:${NC} $music_ily found ..."
    else
        echo -e "${RED_BOLD}FAIL:${NC} $music_ily missing ..."
        result=99
    fi
    if [ -f music.ly ]; then
        echo -e "${GREEN_BOLD}PASS:${NC} $music_ly found ..."
    else
        echo -e "${RED_BOLD}FAIL:${NC} $music_ly missing ..."
        result=99
    fi
    if [ -f music.midi ]; then
        echo -e "${GREEN_BOLD}PASS:${NC} $music_midi found ..."
    else
        echo -e "${RED_BOLD}FAIL:${NC} $music_midi missing ..."
        result=99
    fi
    if [ -f music.pdf ]; then
        echo -e "${GREEN_BOLD}PASS:${NC} $music_pdf found ..."
    else
        echo -e "${RED_BOLD}FAIL:${NC} $music_pdf missing ..."
        result=99
    fi
    # print contents results
    if [ $clicktrack_midi_same ]; then
        echo -e "${GREEN_BOLD}PASS:${NC} $clicktrack_midi same ..."
    else
        echo -e "${RED_BOLD}FAIL:${NC} $clicktrack_midi changed ..."
    fi
    if [ -f layout.py ]; then
        if [ $layout_ly_same ]; then
            echo -e "${GREEN_BOLD}PASS:${NC} $layout_ly same ..."
        else
        echo -e "${RED_BOLD}FAIL:${NC} $layout_ly changed ..."
        fi
    fi
    if [ $music_ily_same ]; then
        echo -e "${GREEN_BOLD}PASS:${NC} $music_ily same ..."
    else
        echo -e "${RED_BOLD}FAIL:${NC} $music_ily changed ..."
    fi
    if [ $music_ly_same ]; then
        echo -e "${GREEN_BOLD}PASS:${NC} $music_ly same ..."
    else
        echo -e "${RED_BOLD}FAIL:${NC} $music_ly changed ..."
    fi
    if [ $music_midi_same ]; then
        echo -e "${GREEN_BOLD}PASS:${NC} $music_midi same ..."
    else
        echo -e "${RED_BOLD}FAIL:${NC} $music_midi changed ..."
    fi
    # check result
    if [ $result ]; then
        exit $result
    fi
    echo
done
