#! /usr/bin/env python
import os
import sys

import baca

for string in sys.argv[1:]:
    if string.startswith("--directory="):
        directory = string[12:]
        break
else:
    directory = os.getcwd()
baca.build.handle_build_tags(directory)
