#! /usr/bin/env python
import os
import sys

import baca

directory = os.getcwd()
directory = baca.Path(directory)
skip_segment_collection = "--skip-segment-collection" in sys.argv[1:]
baca.build.interpret_build_music(
    directory,
    skip_segment_collection=skip_segment_collection,
)
