#! /usr/bin/env python
import os
import pathlib

import baca

if __name__ == "__main__":
    directory = os.getcwd()
    directory = pathlib.Path(directory)
    arguments = baca.build.arguments("--debug-sections", "--skip-section-collection")
    baca.build.interpret_build_music(
        directory,
        debug_sections=arguments.debug_sections,
        skip_section_collection=arguments.skip_section_collection,
    )
