#! /usr/bin/env python
# revision 1

import os
import sys

result = os.popen('lilypond --version').readlines( )
first_line = result[0]
first_line = first_line.strip('\n')
version = first_line.split(' ')[-1]
sys.stdout.write(version)
