#! /usr/bin/env python

'''Equivalent to iotools.ly() in Abjad.'''

import glob
import os

os.system('clear')
glob_string = os.path.join('/', 'Users', 'trevorbaca', '.abjad', 'output', '*.ly')
last = glob.glob(glob_string)[-1]
os.system('vim %s' % last)
