#! /usr/bin/env python
r'''No equivalent in Abjad.
'''
import glob
import os


os.system('clear')
glob_string = os.path.join(
    '/', 'Users', 'trevorbaca', '.abjad', 'output', '*.ly')
last = glob.glob(glob_string)[-1]
os.system('lily %s' % last)