#! /usr/bin/env python
# revision 1

import glob
import os


LILYPONDOUTPUT = os.environ.get('LILYPONDOUTPUT')

start_directory = os.path.abspath('.')
os.chdir(LILYPONDOUTPUT)
last = glob.glob(LILYPONDOUTPUT + '*.ly')[-1]
os.system('lily %s' % last)
os.chdir(start_directory)
