#! /usr/bin/env python
import os
import sys

LILYPOND = "/Applications/LilyPond.app/Contents/Resources/bin/lilypond"
_STYLESHEETS = "/Users/trevorbaca/abjad/docs/source/_stylesheets"

command = f"{LILYPOND}"
command += f" --include={_STYLESHEETS}"
command += f" -dno-point-and-click"
command += f" {sys.argv[1]}"
os.system(command)
