#! /usr/bin/env python

'''Equivalent to iotools.pdf( ) in Abjad.'''

import glob
import os

os.system('clear')
glob_string = os.path.join('/', 'Users', 'trevorbaca', '.abjad', 'output', '*.pdf')
last = glob.glob(glob_string)[-1]
os.system('open %s' % last)
