#! /usr/bin/env python
import os
import pathlib
import sys

import baca

directory = os.getcwd()
directory = pathlib.Path(directory)
do_not_interpret_ly = "--do-not-interpret-ly" in sys.argv[1:]
timing = "--timing" in sys.argv[1:]
baca.build.make_segment_pdf(
    directory,
    do_not_interpret_ly=do_not_interpret_ly,
    timing=timing,
)
