#! /usr/bin/env python
import os
import sys


class_package_path_name = sys.argv[1]
class_name = class_package_path_name.split(os.path.sep)[-1]
os.mkdir(class_package_path_name)

class_package_test_path_name = os.path.join(class_package_path_name, 'test')
os.mkdir(class_package_test_path_name)

initializer_file_name = os.path.join(class_package_path_name, '__init__.py')
initializer = open(initializer_file_name, 'w')
initializer.write('from {0} import {0}\n'.format(class_name))
initializer.close()

class_file_name = os.path.join(class_package_path_name, '{}.py'.format(class_name))
class_file = open(class_file_name, 'w')
class_file.write('\n\n\n')
class_file.write('class {}(object):\n'.format(class_name))
class_file.write('\n')
class_file.write('    pass\n')
class_file.close()
print '{} package created.'.format(class_package_path_name)
