#! /usr/bin/env python
import os
import shutil
import sys

import helpers

import abjad
import baca


def _make_segment_ly(directory):
    assert directory.is_segment()
    definition = directory / "definition.py"
    if not definition.is_file():
        print(f"Can not find {definition.trim()} ...")
        sys.exit(-1)
    ly = directory / "illustration.ly"
    if ly.exists():
        print(f"Removing {ly.trim()} ...")
    maker = directory / "__make_segment_ly__.py"
    maker.remove()
    with abjad.FilesystemState(remove=[maker]):
        print(f"Writing {maker.trim()} ...")
        helpers._copy_boilerplate(directory, maker.name)
        previous_segment = directory.get_previous_package()
        if previous_segment is None:
            statement = "previous_metadata = None"
            persist_statement = "previous_persist = None"
        else:
            metadata = previous_segment / "__metadata__.py"
            statement = f'file = baca.Path("{metadata}")'
            statement += "\n        lines = file.read_text()"
            statement += "\n        exec(lines)"
            statement += "\n        previous_metadata = metadata"
            persist = previous_segment / "__persist__.py"
            persist_statement = f'file = baca.Path("{persist}")'
            persist_statement += "\n        lines = file.read_text()"
            persist_statement += "\n        exec(lines)"
            persist_statement += "\n        previous_persist = persist"
        template = maker.read_text()
        template = template.format(
            previous_segment_metadata_import_statement=statement,
            previous_segment_persist_import_statement=persist_statement,
        )
        maker.write_text(template)
        print(f"Interpreting {maker.trim()} ...")
        result = helpers._interpret_file(maker)
        if ly.is_file():
            print(f"Found {ly.trim()} ...")
        print(f"Removing {maker.trim()} ...")
    stdout_lines, stderr_lines, exit_code = result
    if exit_code:
        for string in stderr_lines:
            print(string)


for string in sys.argv[1:]:
    if string.startswith("--directory="):
        directory = string[12:]
        break
else:
    directory = os.getcwd()
directory = baca.Path(directory)
if not (directory.is_segment() or directory.is_segments()):
    print("Must call script in segment or segments directory ...")
    sys.exit(-1)
if directory.is_segment():
    _make_segment_ly(directory)
else:
    assert directory.is_segments()
    if "--directory" in sys.argv[1:]:
        print("Do not use --directory in segments directory ...")
        sys.exit(-1)
    exit = 0
    paths = directory.list_paths()
    paths = [_ for _ in paths if _.is_dir()]
    for i, path in enumerate(paths):
        _make_segment_ly(path)
        if i + 1 < len(paths):
            print()
