#! /usr/bin/env bash

paths=$(find . -name $1 | sort)
for path in $paths; do
    echo Opening $path ...
done
path_count=$(echo $paths | wc -w | xargs)
prompt="${path_count} files ok?> "
read -p "$prompt" confirm && [[ $confirm == y ]] || exit 1
open $paths
