#! /usr/bin/env python

import os

os.system('clear')

dirs = (
   '/Users/trevorbaca/Documents/articles',
   '/Users/trevorbaca/Documents/harvard',
   '/Users/trevorbaca/Documents/math',
   '/Users/trevorbaca/Documents/reference',
   '/Users/trevorbaca/Documents/travel',
   '/Users/trevorbaca/Documents/vitae',
   '/Users/trevorbaca/friends',)

for dir in dirs:
   name = dir.split('/')[-1]
   print '%s ...' % name
   os.system('svn st -u %s' % dir)
   print ''
