#! /usr/bin/env python

import os

os.system('clear')
other = os.path.join('/', 'Users', 'trevorbaca', 'Documents', 'other')
for dir in os.listdir(other):
   if not dir.startswith('.'):
      print '%s ...' % dir
      full_dir = os.path.join(other, dir)
      os.system('svn st -u %s' % full_dir)
      print ''
