#! /usr/bin/env python

import os

os.system('clear')

dirs = (
   '/Users/trevorbaca/Documents/other/articles',
   '/Users/trevorbaca/Documents/other/math',
   '/Users/trevorbaca/Documents/other/monographs',
   '/Users/trevorbaca/Documents/other/reference',
   '/Users/trevorbaca/Documents/other/travel',
   '/Users/trevorbaca/Documents/other/vitae',
   )

for dir in dirs:
   name = dir.split('/')[-1]
   print '%s ...' % name
   os.system('svn st -u %s' % dir)
   print ''
