#! /usr/bin/env bash

source ~/baca/scr/lib-replacement-commands
source ~/baca/scr/lib-score-navigation

clear
group="OK"

case $1 in
    1)
        aka; gg; ipm
        akl; gg; ipm
        ani; gg; ipm
        dor; gg; ipm
        fab; gg; ipm
        ;;
    2)
        har; gg; ipm
        hij; gg; ipm
        hui; gg; ipm
        ikr; gg; ipm
        ins; gg; ipm
        kha; gg; ipm
        kru; gg; ipm
        ;;
    3)
        mra; gg; ipm
        myr; gg; ipm
        nae; gg; ipm
        rec; gg; cd 01; ipm --do-not-open
        str; gg; ipm
        tra; gg; ipm
        ;;
    *)
        echo Group not found: "$1"
        group="BAD"
        ;;
esac

if [[ "$group" = "OK" ]]; then
    say "Rerendered segments for score group ${1}."
fi
