#! /usr/bin/env python
import baca


studio = baca.scf.StudioProxy()

while True:
    try:
        studio.work_in_studio()
    except EOFError:
        print '\n'
        break
    except baca.scf.StudioException:
        pass

#/Users/trevorbaca/Documents/other/baca/scf/scf.py $@
