#! /usr/bin/env python

import os
import sys

base = 'grep -Irn "%s" /Users/trevorbaca/Documents/scores/%s/* | grep -v svn | grep -v crito-1 | grep -v crito-2'

os.system('clear')

os.system('grep -Irn "%s" /Users/trevorbaca/Documents/baca | grep -v svn' %
   sys.argv[1])

scores = os.listdir(os.getenv('SCORES'))
scores = [x for x in scores if not x.startswith('.')]
for score in scores:
   os.system(base % (sys.argv[1], score))
