#! /usr/bin/env python

import os
import sys

base = 'grep -Irn "%s" /Users/trevorbaca/Documents/work/%s/* | grep -v svn | grep -v crito-1 | grep -v crito-2'

os.system('clear')

for work in ('cary', 'sekka', 'lidercfeny', 'manifolds', ):
   os.system(base % (sys.argv[1], work))
