#! /usr/bin/env python

import os

SCORES = '/Users/trevorbaca/Documents/scores/'
os.system('clear')

dirs = (
   'recursif',
   'hijinks', 
   'cary',
   'sekka', 
   'lidercfeny', 
   'manifolds', 
   'territoires', 
   'desir',
   )

for dir in dirs:
   print '%s ...' % dir
   os.system('svn st -u %s' % os.path.join(SCORES, dir))
   print ''
