#! /usr/bin/env bash

source path-manipulation

bb() {
    clear;
    contents_directory=$(find_score_contents_directory)
    cd ${contents_directory}/builds
    ls;
}
export -f bb

cc() {
    clear;
    contents_directory=$(find_score_contents_directory)
    cd ${contents_directory}
    ls;
}
export -f cc

dd() {
    clear;
    contents_directory=$(find_score_contents_directory)
    cd ${contents_directory}/distribution
    ls;
}
export -f dd

ee() {
    clear;
    contents_directory=$(find_score_contents_directory)
    cd ${contents_directory}/etc
    ls;
}
export -f ee

gg() {
    clear;
    contents_directory=$(find_score_contents_directory)
    cd ${contents_directory}/segments
    ls;
}
export -f gg

yy() {
    clear;
    contents_directory=$(find_score_contents_directory)
    cd ${contents_directory}/stylesheets
    ls;
}
export -f yy

ww() {
    clear;
    contents_directory=$(find_score_contents_directory)
    wrapper_directory=$(dirname "$contents_directory")
    cd ${wrapper_directory}
    ls;
}
export -f ww

MM() {
    clear;
    directory=$(get_next_score "$PWD");
    cd $directory
}

M() {
    clear;
    directory=$(get_next_sibling_directory "$PWD");
    cd $directory
}

NN() {
    clear;
    directory=$(get_previous_score "$PWD");
    cd $directory
}

N() {
    clear;
    directory=$(get_previous_sibling_directory "$PWD");
    cd $directory
}
