#! /usr/bin/env python

import os

SCORESDIR = '/Users/trevorbaca/Documents/scores/'
os.system('clear')

print 'baca ...'
os.system('svn st -u /Users/trevorbaca/Documents/baca')
print ''

dirs = (
   'desir',
   'territoires', 
   'manifolds', 
   'lidercfeny', 
   'sekka', 
   'cary',
   'hijinks', 
   'recursif')

for dir in dirs:
   print '%s ...' % dir
   os.system('svn st -u %s' % os.path.join(SCORESDIR, dir))
   print ''
