#! /usr/bin/env python

import os
import sys

WORKDIR = '/Users/trevorbaca/Documents/work/'
os.system('clear')

print 'baca ...'
os.system('svn st -u /Users/trevorbaca/Documents/baca')
print ''

for dir in ('territoires', 'manifolds', 'lidercfeny', 'sekka', 'cary',
   'hijinks', 'recursif'):
   print '%s ...' % dir
   os.system('svn st -u %s' % os.path.join(WORKDIR, dir))
   print ''
