#! /usr/bin/env python
import os
import pathlib
import sys

import baca

if __name__ == "__main__":
    directory = pathlib.Path(os.getcwd())
    undo = "--undo" in sys.argv
    for name in ("layout.ly", "music.ily", "music.ly"):
        file = directory / name
        if file.is_file():
            baca.build.show_annotations(file, undo=undo)
