#! /usr/bin/env python
import os
import pathlib
import sys

import baca

if __name__ == "__main__":
    directory = os.getcwd()
    tag_name, undo = None, False
    for argument in sys.argv[1:]:
        if argument.startswith("--tag="):
            tag_name = argument.removeprefix("--tag=")
        if argument == "--undo":
            undo = True
    if tag_name is None:
        print("Missing mandatory --tag= parameter ...")
        sys.exit(-1)
    file = pathlib.Path(directory) / "music.ily"
    messages = baca.build.show_tag(file, "FIGURE_LABEL", undo=undo)
    if messages:
        print(messages)
