#! /usr/bin/env python
import os
import pathlib
import sys

import abjad
import baca

if __name__ == "__main__":
    directory = os.getcwd()
    tag_name, undo = None, False
    for argument in sys.argv[1:]:
        if argument.startswith("--tag="):
            tag_name = argument.removeprefix("--tag=")
        if argument == "--undo":
            undo = True
    if tag_name is None:
        print("Missing mandatory --tag= parameter ...")
        sys.exit(-1)
    tag = abjad.Tag(tag_name)
    file = pathlib.Path(directory) / "music.ily"
    text, messages = file.read_text(), []
    text = baca.tags.show_tag(text, tag, messages, undo=undo)
    file.write_text(text)
    for message in messages:
        baca.build.print_tags(message)
