#! /usr/bin/env python
import os
import sys

import ide

import abjad


def _git_st(directory):
    with abjad.TemporaryDirectoryChange(directory=directory):
        command = "git status ."
        print(f"Running {command} ...")
        lines = abjad.iox.run_command(command)
        for line in lines:
            if line == "":
                continue
            print(line)
    

if __name__ == "__main__":
    for path in ide.Path("/Users/trevorbaca/Scores").list_paths():
        print(f"{path} ...")
        _git_st(path)
        print()
