#! /usr/bin/env bash

package_name=$(basename $(pwd))
wrapper_directory=$(pwd)
contents_directory=$wrapper_directory/$package_name
segments_directory=$contents_directory/segments
if [ ! -d $segments_directory/01 ]; then
    echo Score contains no segments ...
    exit 0
fi
for segment_directory in $(ls -d "$segments_directory"/[0-9]*); do
    cd $segment_directory
    test-segment
done
