#! /usr/bin/env bash

source lib-path-manipulation

wrapper="$GITHUB_WORKSPACE"
segments=$(realpath "$1")
directories=$(ls -d "$segments"[0-9]*)

echo Wrapper is "$wrapper"
echo Segments is "$segments"
echo Directories is "$directories"
