#! /usr/bin/env python
# revision 1

import os
import re

LILYPONDTEST = os.environ.get('LILYPONDTEST')
pattern = re.compile('\d{4,4}.ly')

all_filenames = os.listdir(LILYPONDTEST)
lilypond_files = [fn for fn in all_filenames if pattern.match(fn)]
last_lilypond_filename = sorted(lilypond_files)[-1]

start_directory = os.path.abspath('.')
os.chdir(LILYPONDTEST)
os.system('vim + %s' % last_lilypond_filename)
os.system('lily %s' % last_lilypond_filename)
os.chdir(start_directory)
