#! /usr/bin/env bash

DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]; then DIR="$PWD"; fi

source "$DIR/lib-path-manipulation"
source "$DIR/make-segment-pdf"

echo GITHUB_WORKSPACE is "$GITHUB_WORKSPACE"
package_name=$(basename "$GITHUB_WORKSPACE")
echo Package name is "$package_name"
echo

wrapper_directory="$GITHUB_WORKSPACE"
echo Wrapper directory is "$wrapper_directory"
echo Contents of wrapper directory:
ls "$wrapper_directory"
echo

contents_directory="$wrapper_directory"/"$package_name"
echo Contents directory is "$contents_directory"
echo Contents of contents directory:
ls "$contents_directory"
echo

segments_directory="$contents_directory"/segments
echo Segments directory is "$segments_directory"
echo Contents of segments directory:
ls "$segments_directory"

segment_directories=$(ls -d "$segments_directory"/[0-9]*)
echo Segment directories are "$segment_directories"

for segment_directory in "$segment_directories"; do
    echo "$segment_directory"
    illustration_ly="$segment_directory"/illustration.ly
    illustration_old_ly="$segment_directory"/illustration.old.ly
    if [ -f "$illustration_ly" ]; then
        cp "$illustration_ly" "$illustration_old_ly"
    fi
    rm "$illustration_ly"
    illustration_ily="$segment_directory"/illustration.ily
    illustration_old_ily="$segment_directory"/illustration.old.ily
    if [ -f "$illustration_ily" ]; then
        cp "$illustration_ily" "$illustration_old_ily"
    fi
    rm "$illustration_ily"
    current_directory=$(pwd)
    cd "$segment_directory"
    echo Calling make_segment_pdf ...
    make_segment_pdf "$segment_directory" --do-not-open
    echo Done with make_segment_pdf ...
    cd "$current_directory"
    if [ -f "$illustration_ly" ]; then
        echo Found "$illustration_ly" ...
    else
        exit -1
    fi
    if [ -f "$illustration_old_ly" ]; then
        echo Found "$illustration_old_ly" ...
    else
        exit -1
    fi
    differences=$(diff -I '^\\version' "$illustration_ly" "$illustration_old_ly")
    if [ -z "$differences" ]; then
        echo Found matching illustration.ly files ...
    else
        echo Found mismatched illustration.ly files ...
        diff -I '^\\version' "$illustration_ly" "$illustration_old_ly"
        exit -1
    fi
    differences=$(diff -I '^\\version' "$illustration_ily" "$illustration_old_ily")
    if [ -z "$differences" ]; then
        echo Found matching illustration.ily files ...
    else
        echo Found mismatched illustration.ily files ...
        diff -I '^\\version' "$illustration_ily" "$illustration_old_ily"
        exit -1
    fi
done
