#! /usr/bin/env python

import os
import sys


def trim_ly_file_for_concatenation(input_file_name):
   output_lines = [ ]
   found_new_score = False
   for line in file(input_file_name, 'r').readlines( ):
      if found_new_score:
         output_lines.append(line)
      ## preserve indentation and replace \new Score << with open skeleton
      elif r'\new Score' in line:
         found_new_score = True
         if 'with' in line:
            print 'WARNING: score contains with-block!\n'
         output_line = line[:line.index(r'\new Score')] + '<<\n'
         output_lines.append(output_line)
   ## remove final close brace that matches \score{ }
   output_lines.pop( )
   output_file_name = 'trimmed-' + input_file_name
   output_lines = ''.join(output_lines)
   file(output_file_name, 'w').write(output_lines)
   print 'New %s written as output.\n' % output_file_name
      

if __name__ == '__main__':
   os.system('clear')
   input_file_name = sys.argv[1]
   trim_ly_file_for_concatenation(input_file_name)
