#! /usr/bin/env python

from abjad.tools import iotools
import os
import sys
import workspaces


# check commandline arguments
if not len(sys.argv) == 4:
   print 'usage: workspace (--data|--score) directory workspace_name'

# parse commandline arguments
type = sys.argv[1][2:]
parent_directory = sys.argv[2]
workspace = sys.argv[3]

assert type in ('data', 'score')

# clear terminal
iotools.clear_terminal()

if type == 'data':
   workspaces.make_data_workspace(parent_directory, workspace)
elif type == 'score':
   workspaces.make_score_workspace(parent_directory, workspace)
else:
   raise ValueError

print ''
