BOW_SPEED = "BOW_SPEED"

CIRCLE_BOW = "CIRCLE_BOW"

CLB = "CLB"

COVERED = "COVERED"

DAMP = "DAMP"

HALF_CLT = "HALF_CLT"

# TODO: remove?
LEFT_BROKEN_REPEAT_TIE_TO = "LEFT_BROKEN_REPEAT_TIE_TO"

MATERIAL = "MATERIAL"

NOT_PARTS = "-PARTS"
NOT_SCORE = "-SCORE"
NOT_SEGMENT = "-SEGMENT"

ONLY_PARTS = "+PARTS"
ONLY_SCORE = "+SCORE"
ONLY_SEGMENT = "+SEGMENT"

PITCH = "PITCH"

REPEAT_TIE = "REPEAT_TIE"  # remove?
RIGHT_BROKEN_TIE_FROM = "RIGHT_BROKEN_TIE_FROM"  # remove?
RHYTHM = "RHYTHM"

SCP = "SCP"
SPAZZOLATO = "SPAZZOLATO"
STRING_NUMBER = "STRING_NUMBER"

TACET = "TACET"
TASTO = "TASTO"
TIE_FROM = "TIE_FROM"  # remove?
TIE_TO = "TIE_TO"  # remove?

VIBRATO = "VIBRATO"
