ALREADY_PITCHED = "ALREADY_PITCHED"
ALLOW_OCTAVE = "ALLOW_OCTAVE"
ALLOW_OUT_OF_RANGE = "ALLOW_OUT_OF_RANGE"
ALLOW_REPEAT_PITCH = "ALLOW_REPEAT_PITCH"

BOW_SPEED = "BOW_SPEED"

CIRCLE_BOW = "CIRCLE_BOW"
CLB = "CLB"
COVERED = "COVERED"

DAMP = "DAMP"
DO_NOT_TRANSPOSE = "DO_NOT_TRANSPOSE"

FERMATA_MEASURE = "FERMATA_MEASURE"
FERMATA_DURATION = "FERMATA_DURATION"

HALF_CLT = "HALF_CLT"
HIDDEN = "HIDDEN"
HIDDEN_NOTE_VOICE = "HIDDEN_NOTE_VOICE"

INTERMITTENT = "INTERMITTENT"

MATERIAL = "MATERIAL"
MOCK = "MOCK"
MULTIMEASURE_REST = "MULTIMEASURE_REST"
MULTIMEASURE_REST_CONTAINER = "MULTIMEASURE_REST_CONTAINER"

NOT_YET_PITCHED = "NOT_YET_PITCHED"
NOT_YET_REGISTERED = "NOT_YET_REGISTERED"
NOTE = "NOTE"

PHANTOM = "PHANTOM"
PHANTOM_MULTIMEASURE_REST = "PHANTOM_MULTIMEASURE_REST"
PHANTOM_NOTE = "PHANTOM_NOTE"
PITCH = "PITCH"

RHYTHM = "RHYTHM"
REMOVE_ALL_EMPTY_STAVES = "REMOVE_ALL_EMPTY_STAVES"
REPEAT_PITCH_CLASS = "REPEAT_PITCH_CLASS"
REST_VOICE = "REST_VOICE"
RIGHT_BROKEN_BEAM = "RIGHT_BROKEN_BEAM"

SCP = "SCP"
SKIP = "SKIP"
SOUNDS_DURING_SEGMENT = "SOUNDS_DURING_SEGMENT"
SPAZZOLATO = "SPAZZOLATO"
STAFF_POSITION = "STAFF_POSITION"
STRING_NUMBER = "STRING_NUMBER"

TEMPORARY_CONTAINER = "TEMPORARY_CONTAINER"
TWO_VOICE = "TWO_VOICE"
THREE_VOICE = "THREE_VOICE"

TASTO = "TASTO"

VIBRATO = "VIBRATO"
