BOW_SPEED = "BOW_SPEED"

CIRCLE_BOW = "CIRCLE_BOW"

CLB = "CLB"

COVERED = "COVERED"

DAMP = "DAMP"

FERMATA_DURATION = "FERMATA_DURATION"

HALF_CLT = "HALF_CLT"

HIDDEN_NOTE_VOICE = "HIDDEN_NOTE_VOICE"

INTERMITTENT = "INTERMITTENT"

LEFT_BROKEN_REPEAT_TIE_TO = "LEFT_BROKEN_REPEAT_TIE_TO"

MATERIAL = "MATERIAL"

MULTIMEASURE_REST_CONTAINER = "MULTIMEASURE_REST_CONTAINER"

NOT_PARTS = "-PARTS"
NOT_SCORE = "-SCORE"
NOT_SEGMENT = "-SEGMENT"

ONLY_PARTS = "+PARTS"
ONLY_SCORE = "+SCORE"
ONLY_SEGMENT = "+SEGMENT"

PHANTOM = "PHANTOM"

PITCH = "PITCH"

REPEAT_TIE = "REPEAT_TIE"
RIGHT_BROKEN_TIE_FROM = "RIGHT_BROKEN_TIE_FROM"
RHYTHM = "RHYTHM"

SCP = "SCP"
SOUNDS_DURING_SEGMENT = "SOUNDS_DURING_SEGMENT"
SPAZZOLATO = "SPAZZOLATO"
STRING_NUMBER = "STRING_NUMBER"

TACET = "TACET"
TEMPORARY_CONTAINER = "TEMPORARY_CONTAINER"
TIE_FROM = "TIE_FROM"
TIE_TO = "TIE_TO"

VIBRATO = "VIBRATO"
