BOW_SPEED = 'BOW_SPEED'

CIRCLE_BOW = 'CIRCLE_BOW'

DAMP = 'DAMP'

HALF_CLT = 'HALF_CLT'

HIDDEN = 'HIDDEN'
HIDDEN_NOTE_VOICE = 'HIDDEN_NOTE_VOICE'

INTERMITTENT = 'INTERMITTENT'

MATERIAL = 'MATERIAL'

MULTIMEASURE_REST_CONTAINER = 'MULTIMEASURE_REST_CONTAINER'

NOT_PARTS = '-PARTS'
NOT_SCORE = '-SCORE'
NOT_SEGMENT = '-SEGMENT'

ONLY_PARTS = '+PARTS'
ONLY_SCORE = '+SCORE'
ONLY_SEGMENT = '+SEGMENT'

PHANTOM = 'PHANTOM'

PITCH = 'PITCH'

SCP = 'SCP'

STRING_NUMBER = 'STRING_NUMBER'

TACET = 'TACET'
