HIDDEN = 'HIDDEN'
HIDDEN_NOTE_VOICE = 'HIDDEN_NOTE_VOICE'

INTERMITTENT = 'INTERMITTENT'

MATERIAL = 'MATERIAL'

MULTIMEASURE_REST_CONTAINER = 'MULTIMEASURE_REST_CONTAINER'

PHANTOM = 'PHANTOM'

PITCH = 'PITCH'
