class AttributeNameEnumeration(object):

    aggregate = 'aggregate'
    articulations = 'articulations'
    duration_in_seconds = 'duration_in_seconds'
    chords = 'chords'
    divisions = 'divisions'
    dynamics = 'dynamics'
    marks = 'marks'
    markup = 'markup'
    pitch = 'pitch'
    pitch_class_application = 'pitch_class_application'
    pitch_classes = 'pitch_classes'
    register = 'register'
    rhythm = 'rhythm'
    tempo = 'tempo'
    time_signatures = 'time_signatures'
    transform = 'transform'
    written_duration = 'written_duration'
