\include "/Users/trevorbaca/abjad/docs/source/_stylesheets/abjad.ily"
#(ly:set-option 'relative-includes #t)
\include "baca-articulations.ily"
\include "baca-boxed-instrument-markups.ily"
\include "baca-circle-bow-markups.ily"
\include "baca-coloring.ily"
\include "baca-dynamics.ily"
\include "baca-markups.ily"
\include "baca-note-heads.ily"
\include "baca-page-layout.ily"
\include "baca-spanners.ily"
